# A Workshop Introduction to NumPy

The Python language is an excellent tool for general-purpose programming, with a highly readable syntax, rich and powerful data types (strings, lists, sets, dictionaries, arbitrary length integers, etc) and a very comprehensive standard library. It was not, however, designed specifically for mathematical and scientific computing. Neither the language nor its standard library have facilities for the efficient representation of multidimensional datasets, tools for linear algebra and general matrix manipulations (essential building blocks of virtually all scientific computing).

For example, Python lists are very flexible containers that can be nested arbitrarily deep and can hold any Python object in them, but they are poorly suited to represent common mathematical constructs like vectors and matrices. It is for this reason that NumPy exists.

## Workshop Objectives

The aim of this workshop is to enable you to:

  - manipulate numerical arrays
  - perform efficient array calculations

## Table of Contents

* [Getting Started with NumPy](#getting-started)
* [Motivation: what are arrays good for?](#motivation)
* [The Array Object](#array-object)
* [Application: Arithmetic and Broadcasting](#arithmetic_and_broadcasting)
* [Application: Statistics](#statistics)
* [Application: Efficiency](#efficiency)
* [Further Reading](#further_reading)

## Style
This workshop is a hands on coding workshop with discussion sections.  It can be treated as an exercise for an individual, but the intent is to work as a group with an instructor.

Topics are introduced, followed by worked examples and exploration suggestions.  These should be attempted individually or in small groups (making sure everyone is keeping their own notes).
Each topic concludes with a review and discussion session for the whole group.

The Jupyter notebook provides each participant with an environment to run code and make notes.  We recommend that you take your own copy of the workshop notebook and customise it through the workshop.
This should provide you with a useful resource to refer back to.

## Getting Started with NumPy <a class="anchor" id="getting-started"></a>
NumPy is the fundamental package for scientific computing with Python. Its primary purpose is to provide a powerful N-dimensional array object; the focus for this workshop.

To begin with let's import NumPy, check where it is being imported from and check the version.

In [1]:
# NumPy is generally imported as 'np'.
import numpy as np
print(np)
print(np.__version__)

<module 'numpy' from '/data/users/lcarroll/miniconda2/envs/NumJup/lib/python2.7/site-packages/numpy/__init__.pyc'>
1.14.2


### Documentation
Here is a link to the NumPy documentation for v1.11:
https://docs.scipy.org/doc/numpy-1.11.0/reference/

There are many online forums with tips and suggestions for solving problems with NumPy, such as http://stackoverflow.com/

### Explore: creating arrays

NumPy provides many different ways to create arrays. These are listed in the documentation at: https://docs.scipy.org/doc/numpy-1.11.0/user/basics.creation.html#arrays-creation.

##### Part 1

Try out some of these ways of creating NumPy arrays. See if you can produce:

* a NumPy array from a list of numbers,
* a 3-dimensional NumPy array filled with a constant value -- either `0` or `1`,
* a NumPy array filled with a constant value -- **not** `0` or `1`. (**Hint:** this can be achieved using the last array you created, or you could use `np.empty` and find a way of filling the array with a constant value),
* a NumPy array of 8 elements with a range of values starting from `0` and a spacing of `3` between each element, and
* a NumPy array of 10 elements that are logarithmically spaced.

In [3]:
x = np.array([2,3,1,0])
x

array([2, 3, 1, 0])

In [5]:
z = np.zeros((2, 3, 5))
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
o = np.ones((2, 3, 5))
o

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [6]:
t = z + 2
t

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [13]:
e = np.empty([5,4])
e

array([[1.24189366e-312, 1.68003110e-316, 8.48798317e-313,
        1.93101617e-312],
       [1.01855798e-312, 9.33678148e-313, 1.01855798e-312,
        9.33678148e-313],
       [1.01855798e-312, 9.33678148e-313, 1.01855798e-312,
        9.33678148e-313],
       [1.01855798e-312, 1.97345609e-312, 2.12199579e-313,
        6.91270508e-310],
       [6.91270142e-310, 6.91270508e-310, 7.90505033e-322,
        2.64948245e-032]])

In [14]:
e.fill(5)
e

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [78]:
range = np.arange(0, 23, step=3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [69]:
lin = np.linspace(0, 21, num=8)
lin

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [26]:
l = np.logspace(1,5,num =5, endpoint=False)
l

array([1.00000000e+01, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04])

In [20]:
N = 10
x1 = np.logspace(0.1, N, endpoint=True)
x2 = np.logspace(0.1, 1, N, endpoint=False)
print(x1)
print(x2)

[1.25892541e+00 2.00466042e+00 3.19213781e+00 5.08302738e+00
 8.09400122e+00 1.28885506e+01 2.05231915e+01 3.26802759e+01
 5.20387110e+01 8.28642773e+01 1.31949626e+02 2.10111092e+02
 3.34572157e+02 5.32758776e+02 8.48342898e+02 1.35086592e+03
 2.15106266e+03 3.42526264e+03 5.45424565e+03 8.68511374e+03
 1.38298136e+04 2.20220195e+04 3.50669472e+04 5.58391470e+04
 8.89159334e+04 1.41586031e+05 2.25455703e+05 3.59006276e+05
 5.71666650e+05 9.10298178e+05 1.44952093e+06 2.30815679e+06
 3.67541279e+06 5.85257434e+06 9.31939576e+06 1.48398179e+07
 2.36303083e+07 3.76279193e+07 5.99171324e+07 9.54095476e+07
 1.51926192e+08 2.41920945e+08 3.85224842e+08 6.13416003e+08
 9.76778110e+08 1.55538080e+09 2.47672365e+09 3.94383164e+09
 6.27999335e+09 1.00000000e+10]
[1.25892541 1.54881662 1.90546072 2.34422882 2.8840315  3.54813389
 4.36515832 5.37031796 6.60693448 8.12830516]


##### Part 2

How could you change the shape of the 8-element array you created previously to have shape `(2, 2, 2)`? **Hint:** this can be done without creating a new array.

In [79]:
range.reshape(2,2,2)

array([[[ 0,  3],
        [ 6,  9]],

       [[12, 15],
        [18, 21]]])

## Motivation: what are arrays good for? <a class="anchor" id="motivation"></a>

### Extensive Features


NumPy provides routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### Fast Calculations

It is a lot faster than Python alone for numerical computing tasks.

Element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code. 

### Clear Syntax

In NumPy,

```python
c = a * b
```

calculates the element-wise product of `a` and `b`, at near-C speeds, but with the code simplicity we expect from the Python language.

This demonstrates a core feature of NumPy, called **vectorization**. This removes the need for loops iterating through elements of arrays, which can make code easier to read, as well as performing fast calculations.

### Interfacing to other Libraries

Many scientific Python libraries use NumPy as their core array representation. From plotting libraries such as matplotlib, to parallel processing libraries such as Dask, to data interoperability libraries such as Iris, NumPy arrays are at the core of how these libraries operate and communicate.

## The Array Object <a class="anchor" id="array-object"></a>

The multidimensional array object is the core of NumPy's power.  Let us explore this object some more.

### Array properties

Let's create a NumPy array and take a look at some of its properties.

In [80]:
arr = np.ones((3, 2, 4))

print("Array shape:", arr.shape)
print("Array element dtype:", arr.dtype)

('Array shape:', (3, 2, 4))
('Array element dtype:', dtype('float64'))


#### Exercise

##### Part 1

Use the code cells below to explore features of these arrays.

* What is the `type` of each of the arrays created above? (Hint: you can find the type of an object in Python using `type(<object>)`, where `<object>` is replaced with the name of the variable containing the object.)
* Look this type up in the NumPy documentation (see https://docs.scipy.org/doc/numpy-1.11.0/reference/generated/numpy.ndarray.html#numpy.ndarray).

In [81]:
type(lin)

numpy.ndarray

In [82]:
lin.dtype

dtype('float64')

In [83]:
lin.shape

(8,)

In [84]:
e.shape

(5, 4)

In [85]:
e.dtype

dtype('float64')

In [87]:
e.ndim

2

In [86]:
range.dtype

dtype('int64')

##### Part 2

Consider the following NumPy array properties:

* `ndim`,
* `nbytes`,
* `size`,
* `T`.

For each of these properties:

* Use information from the array documentation to find out more about each array property.
* Apply each property to the array `arr` defined above. Can you explain the results you get in each case?

Be ready to feed your results back to the group!

In [89]:
print(arr.ndim)
print(arr.nbytes)
print(arr.size)

3
192
24


In [92]:
print("Arr")
print(arr)
print("T")
print(arr.T)

Arr
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
T
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### Indexing

You can index NumPy arrays in the same way as other Python objects, by using square brackets `[]`. This means we can index to retrieve a single element, multiple consecutive elements, or a more complex sequence:

In [95]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("arr --", arr)
print("arr[2] --", arr[2])
print("arr[2:5] --", arr[2:5])
print("arr[::2] --", arr[::2])

('arr --', array([1, 2, 3, 4, 5, 6]))
('arr[2] --', 3)
('arr[2:5] --', array([3, 4, 5]))
('arr[::2] --', array([1, 3, 5]))


You can also index multidimensional arrays in a logical way using an enhanced indexing syntax. Remember that Python uses zero-based indexing!

In [96]:
lst_2d = [[1, 2, 3], [4, 5, 6]]
arr_2d = np.array(lst_2d)

print("2D list:")
print(lst_2d)

2D list:
[[1, 2, 3], [4, 5, 6]]


In [97]:
print("2D array:")
print(arr_2d)

2D array:
[[1 2 3]
 [4 5 6]]


In [98]:
print("Single array element:")
print(arr_2d[1, 2])

Single array element:
6


In [99]:
print("Single row:")
print(arr_2d[1])
print("First two columns:")
print(arr_2d[:, :2])

Single row:
[4 5 6]
First two columns:
[[1 2]
 [4 5]]


Numpy provides syntax to index conditionally, based on the data in the array.

You can pass in an array of True and False values (a boolean array), or, more commonly, a condition that returns a boolean array.

In [100]:
print arr_2d

[[1 2 3]
 [4 5 6]]


In [101]:
bools = arr_2d % 2 == 0
print bools

[[False  True False]
 [ True False  True]]


In [102]:
print(arr_2d[bools])

[2 4 6]


#### Exercise

##### Part 1

Why do these indexing examples give the stated results?

 * result of `arr_2d[1, 0]` is `4`
 * result of `arr_2d[0]` is `[1, 2, 3]`
 * result of `arr_2d[1, 1:]` is `[5, 6]`
 * result of `arr_2d[0:, ::2]` is `[[1, 3], [4, 6]]`

In [103]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


##### Part 2

How would you index `arr_2d` to retrieve:

 * the third value: resulting in `3`
 * the second row: resulting in `[4, 5, 6]` 
 * the first column: resulting in `[1, 4]`
 * the first column, retaining the outside dimension: resulting in `[[1, 4]]`

In [104]:
arr_2d[0,2]

3

In [106]:
print(arr_2d[1])

[4 5 6]


In [107]:
arr_2d[:,0]

array([1, 4])

In [130]:
arr_2d[:,0]

array([1, 4])

In [121]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
x = np.array([[ 0,  1,  2],
            [ 3,  4,  5],
            [ 6,  7,  8],
            [ 9, 10, 11]])

In [123]:
x[1:1]

array([], shape=(0, 3), dtype=int64)

### Arrays are not lists

Question: why do the following examples produce different results?

In [131]:
print(lst_2d[0:2][1])
print(arr_2d[0:2, 1])

[4, 5, 6]
[2 5]


The result we just received points to an important piece of learning, which is that in most cases NumPy arrays behave very differently to Python lists. Let's explore the differences (and some similarities) between the two.

#### dtype

A NumPy array has a fixed data type, called `dtype`.  This is the type of all the elements of the array.  

This is in contrast to Python lists, which can hold elements of different types.

#### Exercise

* What happens in Python when you add an integer to a float?
* What happens when you put an integer into a NumPy float array?
* What happens when you do numerical calculations between arrays of different types?


In [133]:
type(1)

int

In [134]:
type(1.1)

float

In [135]:
type(1+1.1)

float

In [136]:
integer = np.array([1,2,3,4])
integer.dtype

dtype('int64')

In [138]:
float = np.array([1.1,2.1,3.1,4.1])
float.dtype

dtype('float64')

In [140]:
total = integer + float
print(total)
print(total.dtype)

[2.1 4.1 6.1 8.1]
float64


In [146]:
integer[0]=1.7
print(integer)
print(integer.dtype)

[1 2 3 4]
int64


In [147]:
float[0] = 4
print(float)
print(float.dtype)

[4.  2.1 3.1 4.1]
float64


In [151]:
float = np.append(float, [55])
print(float)
print(float.dtype)

[ 4.   2.1  3.1  4.1 55. ]
float64


### Generating 2D coordinate arrays

A common requirement of NumPy arrays is to generate arrays that represent the coordinates of our data.

When orthogonal 1d coordinate arrays already exist, NumPy's meshgrid function is very useful:

In [154]:
x = np.linspace(0, 9, 3)
y = np.linspace(4, 8, 3)
x2d, y2d = np.meshgrid(x, y)
print x2d
print y2d

[[0.  4.5 9. ]
 [0.  4.5 9. ]
 [0.  4.5 9. ]]
[[4. 4. 4.]
 [6. 6. 6.]
 [8. 8. 8.]]


#### The Array Object: Summary of key  points
 * properties : `shape`, `dtype`
 * arrays are homogeneous, all elements have the same type: `dtype`
 * creation : `array([list])`, `ones`, `zeros`, `arange`, `linspace`:
  * indexing arrays to produce further arrays: views on the original arrays
  * multi-dimensional indexing and conditional indexing

 * combinations to form 2D arrays: `meshgrid`
 

## Application: Arithmetic and Broadcasting<a class="anchor" id="app-calc"></a>

### Elementwise Arithmetic <a class="anchor" id="arithmetic_and_broadcasting"></a>

You can use NumPy to perform arithmetic operations between two arrays in an element-by-element fashion.

In [155]:
arr1 = np.arange(4)
arr2 = np.arange(4)

print('{} + {} = {}'.format(arr1, arr2, arr1 + arr2))

[0 1 2 3] + [0 1 2 3] = [0 2 4 6]


#### Exercise 

Explore arithmetic operations between arrays:

* Create a number of arrays of different shapes and dtypes. Make sure some of them include values of `0`.
* Make use of all the basic Python mathematical operators (i.e. `+`, `-`, `*`, `/`, `//`, `%`).

What operations work? What operations do not work? Can you explain why operations do or do not work?

In [ ]:
#think this is ok

It makes intrinsic sense that you should be able to add a constant to all values in an array:

In [156]:
arr = np.arange(4)
const = 5

print("Original array: {}".format(arr))
print("")
print("Array + const: {}".format(arr + const))

Original array: [0 1 2 3]

Array + const: [5 6 7 8]


### Broadcasting

There are times when you need to perform calculations between NumPy arrays of different sizes.

For example, suppose you have maximum temperatures from each of three recording stations, recorded on two separate days.

In [157]:
daily_records = np.array([[12, 14, 11], [11, 12, 15]])

print('raw data:')
print(daily_records)

raw data:
[[12 14 11]
 [11 12 15]]


Each station is known to overstate the maximum recorded temperature by a different known constant value. You wish to subtract the appropriate offset from each station's values.

You can do that like this:

In [158]:
offset = np.array([2, 1, 4])

corrected_records = daily_records - offset

print('corrected values:')
print(corrected_records)

corrected values:
[[10 13  7]
 [ 9 11 11]]


NumPy allows you to do this easily using a powerful piece of functionality called **broadcasting**.

Broadcasting is a way of treating the arrays ***as if*** they had the same dimensions, and thus have elements all corresponding.  It is then easy to perform the calculation, element-wise.  
It does this by matching dimensions in one array to the other where possible, and using repeated values where there is no corresponding dimension in the other array.

#### Rules of Broadcasting

Broadcasting applies these three rules:

1.    If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

1.    If the shape of the two arrays does not match in any dimension, either array with shape equal to 1 in a given dimension is stretched to match the other shape.

1.    If in any dimension the sizes disagree and neither has shape equal to 1, an error is raised.

Note that all of this happens without ever actually creating the expanded arrays in memory! This broadcasting behavior is in practice enormously powerful, especially given that when NumPy broadcasts to create new dimensions or to 'stretch' existing ones, it doesn't actually duplicate the data. In the example above the operation is carried out as if the scalar 1.5 was a 1D array with 1.5 in all of its entries, but no actual array is ever created. This can save lots of memory in cases when the arrays in question are large. As such this can have significant performance implications.

![Illustration of broadcasting](../images/fig_broadcast_visual_1.png)

([image source](http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html))

#### Exercise

For the following cases:

* What will be the result of adding `arr1` to `arr2`? 
* What will be the shape of the resulting array?
* What rules of broadcasting are being used?

In [162]:
arr1 = np.ones((2, 3))
arr2 = np.ones((2, 1))

print("Arr1")
print(arr1)
print("")
print("Arr2")
print(arr2)
print("")
print("Arr3")

arr3 = arr1 + arr2
print(arr3)
print(arr3.shape)

Arr1
[[1. 1. 1.]
 [1. 1. 1.]]

Arr2
[[1.]
 [1.]]

Arr3
[[2. 2. 2.]
 [2. 2. 2.]]
(2, 3)


In [163]:
arr1 = np.ones((2, 3))
arr2 = np.ones(3)

print("Arr1")
print(arr1)
print("")
print("Arr2")
print(arr2)
print("")
print("Arr3")

arr3 = arr1 + arr2
print(arr3)
print(arr3.shape)

Arr1
[[1. 1. 1.]
 [1. 1. 1.]]

Arr2
[1. 1. 1.]

Arr3
[[2. 2. 2.]
 [2. 2. 2.]]
(2, 3)


In [164]:
arr1 = np.ones((1, 3))
arr2 = np.ones((2, 1))

print("Arr1")
print(arr1)
print("")
print("Arr2")
print(arr2)
print("")
print("Arr3")

arr3 = arr1 + arr2
print(arr3)
print(arr3.shape)

Arr1
[[1. 1. 1.]]

Arr2
[[1.]
 [1.]]

Arr3
[[2. 2. 2.]
 [2. 2. 2.]]
(2, 3)


In [165]:
arr1 = np.ones((1, 3))
arr2 = np.ones((1, 2))

print("Arr1")
print(arr1)
print("")
print("Arr2")
print(arr2)
print("")
print("Arr3")

arr3 = arr1 + arr2
print(arr3)
print(arr3.shape)

Arr1
[[1. 1. 1.]]

Arr2
[[1. 1.]]

Arr3


ValueError: operands could not be broadcast together with shapes (1,3) (1,2) 

#### Reshaping arrays to aid broadcasting

NumPy allows you to change the shape of an array, so long as the total number of elements in the array does not change. For example, we could reshape a flat array with 12 elements to a 2D array with shape `(2, 6)`, or `(3, 2, 2)`, or even `(3, 4, 1)`. We could not, however, reshape it to have shape `(2, 5)`, because the total number of elements would not be kept constant.

Now suppose you want to apply a correction for each day.

For example, you might try :


In [166]:
days_adjust = np.array([1.5, 3.7])
adjusted = daily_records - days_adjust

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

but that results in a `ValueError`. Clearly, this doesn't work !

#### Exercise

With reference to the above rules of broadcasting:
 1. describe why the above attempt to subtract `days_adjust` fails
 1. work out how you can modify the 'days_adjust' array to get the desired result.  
    Hint: imagine how the 'days_adjust' values *should* look, when expanded to match the dimensions of 'daily_records'.

In [167]:
daily_records

array([[12, 14, 11],
       [11, 12, 15]])

In [175]:
days_adjust

array([1.5, 3.7])

In [173]:
re_adjust = days_adjust.reshape(2,1)
print(re_adjust)

[[1.5]
 [3.7]]


In [174]:
daily_records - re_adjust

array([[10.5, 12.5,  9.5],
       [ 7.3,  8.3, 11.3]])

#### Exercise 

Sometimes an operation will produce a result, but not the one you wanted.

For example, suppose we have :
```python
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
```

and we wish to add 0, 100 and 400 ***to the rows***.
That is,

```python
B = np.array([0, 100, 400])
# and...
desired_result = np.array([[  1,   2,   3],
                           [104, 105, 406],
                           [407, 408, 409]])
```

##### Questions:

 1. What will be the result of adding A to B directly?
 1. How can you perform the correct calculation on `A` and `B` to get `desired_result`?

In [176]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [177]:
B = np.array([0, 100, 400])

In [178]:
bad = A + B
print(bad)

[[  1 102 403]
 [  4 105 406]
 [  7 108 409]]


In [179]:
re_B = B.reshape(3,1)
print(re_B)

[[  0]
 [100]
 [400]]


In [180]:
A + re_B

array([[  1,   2,   3],
       [104, 105, 106],
       [407, 408, 409]])

#### Arithmetic and Broadcasting: Summary of key  points

 * arithmetic operations are performed in an element-by-element fashion,
 * operations can be performed between arrays of different shapes,
 * the arrays' dimensions are aligned according to fixed rules; where one input lacks a given dimension, values are repeated,
 * reshaping can be used to get arrays to combine as required.

## Application: Statistics and Masked Arrays <a class="anchor" id="statistics"></a>

### Statistics

Numpy arrays support many common statistical calculations. For a list of common operations, see : https://docs.scipy.org/doc/numpy/reference/routines.statistics.html.

The simplest operations consist of calculating a single statistical value from an array of numbers -- such as a mean value, a variance or a minimum.

For example:

In [181]:
a = np.arange(12).reshape((3, 4))
mean = np.mean(a)
print(a)
print(mean)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5


Used without any further arguments, statistical functions simply reduce the whole array to a single value.  In practice, however, we very often want to calculate statistics over only *some* of the dimensions.

The most common requirement is to calculate a statistic along a single array dimension, while leaving all the other dimensions intact.   This is referred to as "collapsing" or "reducing" the chosen dimension.

This is done by adding an "axis" keyword specifying which dimension, such as `np.min(data, axis=1)`. 

For example, recall that the above "daily_records" data varies over 2 timepoints and 3 locations, mapped to array dimensions 0 and 1 respectively:

```python
print(daily_records)
[[12 14 11]
 [11 12 15]]
```

For this data, by adding the `axis` keyword, we can calculate either...
  * using `axis=0`: a statistic **over both days, for each station**, or
  * using `axis=1`: a statistic **over all three stations, for each day**.

For most statistical functions (but not all), the "axis" keyword will also accept multiple dimensions, e.g. `axis=(0, 2)`.  
Remember also that the *default* statistical operation, as seen above, is to collapses over _all_ dimensions, reducing the array to a single value.  This is equivalent to specifying `axis=None`.

#### Exercise 

* What other similar statistical operations exist (see above link) ?
* A mean value can also be calculated with `<array>.mean()`.  Is that the same thing ?
* produce the two kinds of single-axis average mentioned above -- that is:
   1. over all days at each station, 
   2. over all stations for each day.
* Create a sample 3-D array, to represent air temperature at given times, X and Y positions :
   1. how can you form a mean over all X and Y at each timestep ?  
   1. what shape does such result have ?
   1. how can you calculate the `np.ptp` statistic of this data in a similar form, i.e. for all X and Y at each timestep ?  
     N.B. `ptp` means a peak-to-peak range, i.e. "max(data) - min(data)".

amin(a[, axis, out, keepdims]) 	Return the minimum of an array or minimum along an axis.
amax(a[, axis, out, keepdims]) 	Return the maximum of an array or maximum along an axis.
nanmin(a[, axis, out, keepdims]) 	Return minimum of an array or minimum along an axis, ignoring any NaNs.
nanmax(a[, axis, out, keepdims]) 	Return the maximum of an array or maximum along an axis, ignoring any NaNs.
ptp(a[, axis, out]) 	Range of values (maximum - minimum) along an axis.
percentile(a, q[, axis, out, ...]) 	Compute the qth percentile of the data along the specified axis.
nanpercentile(a, q[, axis, out, .
median(a[, axis, out, overwrite_input, keepdims]) 	Compute the median along the specified axis.
average(a[, axis, weights, returned]) 	Compute the weighted average along the specified axis.
mean(a[, axis, dtype, out, keepdims]) 	Compute the arithmetic mean along the specified axis.
std(a[, axis, dtype, out, ddof, keepdims]) 	Compute the standard deviation along the specified axis.
var(a[, axis, dtype, out, ddof, keepdims]) 	Compute the variance along the specified axis.
nanmedian(a[, axis, out, overwrite_input, ...]) 	Compute the median along the specified axis, while ignoring NaNs.
nanmean(a[, axis, dtype, out, keepdims]) 	Compute the arithmetic mean along the specified axis, ignoring NaNs.
nanstd(a[, axis, dtype, out, ddof, keepdims]) 	Compute the standard deviation along the specified axis, while ignoring NaNs.
nanvar(a[, axis, dtype, out, ddof, keepdims]) 	Compute the variance along the specified axis, while ignoring NaNs.

In [182]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
print(a.mean())

5.5


In [185]:
print(np.mean(a))

5.5


In [190]:
print(a.mean(axis=0))

[4. 5. 6. 7.]


In [189]:
print(np.mean(a, axis=0))

[4. 5. 6. 7.]


In [191]:
print(a.mean(axis=1))

[1.5 5.5 9.5]


In [198]:
long = np.arange(1, 61)
pressure = long.reshape(3,4,5)
print(pressure)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [200]:
time_mean = pressure.mean(axis=(1,2))
print(time_mean)

[10.5 30.5 50.5]


In [258]:
time_peak = np.ptp(pressure, axis=1)
print(time_peak)
#I don't know

[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]


### Masked Arrays

Real-world measurements processes often result in certain datapoint values being uncertain or simply "missing".  This is usually indicated by additional data quality information, stored alongside the data values.

In these cases we often need to make calculations that count only the ***valid*** datapoints.  Numpy provides a special "masked array" type for this type of calculation.

For example, we might know that in our previous `daily_records` data, the value for station-2 on day-1 is invalid.
To represent this missing datapoint, we can make a masked version of the data :

In [220]:
daily_records = np.array([[12, 14, 11], [11, 12, 15]])
masked_data = np.ma.masked_array(daily_records)
masked_data[0, 1] = np.ma.masked
print('masked data:')
print(masked_data)

masked data:
[[12 -- 11]
 [11 12 15]]


The statistics of the masked data version are different:

In [223]:
print('unmasked average = ', np.mean(daily_records))
print('masked average = ', np.ma.mean(masked_data))
print('unmasked masked average = ', np.mean(masked_data))

('unmasked average = ', 12.5)
('masked average = ', 12.2)
('unmasked masked average = ', 12.2)


The `np.ma.masked_array()` function seen above is a simple creation method for masked data.  
The sub-module `np.ma` contains all the NumPy masked-data routines.

Instead of masking selected points, as above, a mask is often specified as a "mask array":  This is a boolean array of the same size and shape as the data, where `False` means a good datapoint and `True` means a masked or missing point.  Such a 'boolean mask' can be passed in the `np.ma.masked_array` creation method, and can be extracted with the `np.ma.getmaskarray()` function.

Note that most file storage formats represent missing data in a _different_ way, using a distinct "missing data" value appearing in the data.  
There is special support for converting between this type of representation and NumPy masked arrays :  Every masked array has a 'fill_value' property and a 'filled()' method to convert between the two.

#### Exercise

  * Create a masked array from the numbers 0-11, where all the values less than 5 are masked.
  * How can you create masked data from an array of positive values where a value of `-1.0` represents 'missing'?
  * What special masked array creation routines exist to do this kind of thing more efficiently?
    * HINT: look up `np.ma.masked_where` and related routines.
  * Use `np.ma.filled()` to create a 'plain' (i.e. unmasked) array from a masked array.
  * How can you create a plain array from a masked array, but using a _different_ fill-value for masked points?
  * Try performing a mathematical operation between two masked arrays. What happens to the 'fill_value' properties when you do so?

In [231]:
Matt = np.arange(12)
Matt_low = Matt<5
print(Matt_low)
print(Matt)
masked_Matt = np.ma.masked_array(Matt, Matt_low)
masked_data[0, 1] = np.ma.masked
print('masked 11:')
print(masked_Matt)

[ True  True  True  True  True False False False False False False False]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
masked 11:
[-- -- -- -- -- 5 6 7 8 9 10 11]


In [260]:
square = np.arange(50)
square[::6] = -1.0
square

array([-1,  1,  2,  3,  4,  5, -1,  7,  8,  9, 10, 11, -1, 13, 14, 15, 16,
       17, -1, 19, 20, 21, 22, 23, -1, 25, 26, 27, 28, 29, -1, 31, 32, 33,
       34, 35, -1, 37, 38, 39, 40, 41, -1, 43, 44, 45, 46, 47, -1, 49])

In [261]:
square_ma = np.ma.masked_values(square, -1.0)
square_ma

masked_array(data=[--, 1, 2, 3, 4, 5, --, 7, 8, 9, 10, 11, --, 13, 14, 15,
                   16, 17, --, 19, 20, 21, 22, 23, --, 25, 26, 27, 28, 29,
                   --, 31, 32, 33, 34, 35, --, 37, 38, 39, 40, 41, --, 43,
                   44, 45, 46, 47, --, 49],
             mask=[ True, False, False, False, False, False,  True, False,
                   False, False, False, False,  True, False, False, False,
                   False, False,  True, False, False, False, False, False,
                    True, False, False, False, False, False,  True, False,
                   False, False, False, False,  True, False, False, False,
                   False, False,  True, False, False, False, False, False,
                    True, False],
       fill_value=-1)

In [ ]:
#how to index just a load of random numbers which I want to list

In [259]:
square[1, 2, 9] = 500

IndexError: too many indices for array

#### Statistics and Masked Arrays: Summary of key points
 * most statistical functions are available in two different forms, as in `array.mean()` and also `np.mean(array)`,
   the choice being mostly a question of style.
 * statistical operations operate over, and remove (or "collapse") the array dimensions that they are applied to.
 * an "axis" keyword specifies operation over dimensions : this can be one; multiple; or all.
   * NOTE: not all operations permit operation over specifically selected dimensions
 * Statistical operations are not really part of Numpy itself, but are defined by the higher-level Scipy project.
 * Missing datapoints can be represented using "masked arrays"
   * these are useful for calculation, but usually require converting to another form for data storage


## Efficiency <a class="anchor" id="efficiency"></a>

### Views on Arrays

NumPy attempts to not make copies of arrays. Many NumPy operations will produce a reference to an existing array, known as a "view", instead of making a whole new array. For example, indexing and reshaping provide a view of the same memory wherever possible.

In [243]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4)

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

('Before\n', array([[0, 1, 2, 3],
       [4, 5, 6, 7]]))
('After\n', array([[1000,    1,    2,    3],
       [   4,    5,    6,    7]]))


What this means is that if one array (`arr`) is modified, the other (`arr_view`) will also be updated :  the same memory is being shared. This is a valuable tool which enables the system memory overhead to be managed, which is particularly useful when handling lots of large arrays. The lack of copying allows for very efficient vectorized operations.

Remember, this behaviour is automatic in most of NumPy, so it requires some consideration in your code, it can lead to some bugs that are hard to track down. For example, if you are changing some elements of an array that you are using elsewhere, you may want to explicitly copy that array before making changes. If in doubt, you can always copy the data to a different block of memory with the `copy()` method.

For example:

In [244]:
arr = np.arange(8)
arr_view = arr.reshape(2, 4).copy()

# Print the "view" array from reshape.
print('Before\n', arr_view)

# Update the first element of the original array.
arr[0] = 1000

# Print the "view" array from reshape again,
# noticing the first value has changed.
print('After\n', arr_view)

('Before\n', array([[0, 1, 2, 3],
       [4, 5, 6, 7]]))
('After\n', array([[0, 1, 2, 3],
       [4, 5, 6, 7]]))


### Loops and Vectorised Operations

We will now explore calculation performance and consider efficiency in terms of processing time.

Firstly let's look at a simple processing time tool that is provided in notebooks; ``%%timeit`` :

In [247]:
%%timeit 
x = range(500)

TypeError: 'numpy.ndarray' object is not callable

Repeat that, specifying only 100 loops and fastest time of 5 runs

In [246]:
%%timeit -n 100 -r 5
x = range(500)

TypeError: 'numpy.ndarray' object is not callable

This gives us an easy way to evaluate performance for implementations ...

In [248]:
rands = np.random.random(1000000).reshape(100, 100, 100)

In [249]:
%%timeit -n 10 -r 5
overPointEightLoop = 0
for i in range(100):
    for j in range(100):
        for k in range(100):
            if rands[i, j, k] > 0.8:
                overPointEightLoop +=1

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
%%timeit -n 10 -r 5
overPointEightWhere = rands[rands > 0.8].size

#### Efficiency: Summary of key  points

 * NumPy enables vectorised calculations that are fast:
   * Python loops are much slower.
 * NumPy can only use the system memory available to hold arrays:
   * very large arrays can result in a `MemoryError`.
 * Many NumPy operations return views on exisiting array:
   * a view shares memory with the original array,
   * changing array contents in place will affect all related views,
   * sometimes it is useful to explicitly `copy` arrays.

### Exercise: trapezoidal integration

In this exercise, you are tasked with implementing the simple trapezoid rule
formula for numerical integration. If we want to compute the definite integral

$$
     \int_{a}^{b}f(x)dx
$$

we can partition the integration interval $[a,b]$ into smaller subintervals. We then
approximate the area under the curve for each subinterval by calculating the area of
the trapezoid created by linearly interpolating between the two function values
at each end of the subinterval:

![Illustration of the trapezoidal rule](../images/trapezoidal_rule.png)

For a pre-computed $y$ array (where $y = f(x)$ at discrete samples) the trapezoidal rule equation is:

$$
   \int_{a}^{b}f(x)dx\approx\frac{1}{2}\sum_{i=1}^{n}\left(x_{i}-x_{i-1}\right)\left(y_{i}+y_{i-1}\right).
$$

In pure python, this can be written as:

    def trapz_slow(x, y):
        area = 0.
        for i in range(1, len(x)):
            area += (x[i] - x[i-1]) * (y[i] + y[i-1])
        return area / 2

#### Part 1

Create two arrays $x$ and $y$, where $x$ is a linearly spaced array in the interval $[0, 3]$ of length 11, and $y$ represents the function $f(x) = x^2$ sampled at $x$.

In [250]:
import numpy as np

x = np.linspace(0, 3, 10)
y = x ** 2

print x
print y

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
[0.         0.11111111 0.44444444 1.         1.77777778 2.77777778
 4.         5.44444444 7.11111111 9.        ]


#### Part 2

Use indexing (not a for loop) to find the 10 values representing $y_{i}+y_{i-1}$ for $i$ between 1 and 11.

Hint: What indexing would be needed to get all but the last element of the 1d array **``y``**. Similarly what indexing would be needed to get all but the first element of a 1d array.

In [251]:
y_roll_sum = y[:-1] + y[1:]
print y_roll_sum

[ 0.11111111  0.55555556  1.44444444  2.77777778  4.55555556  6.77777778
  9.44444444 12.55555556 16.11111111]


#### Part 3

Write a function `trapz(x, y)`, that applies the trapezoid formula to pre-computed values, where `x` and `y` are 1-d arrays. The function should not use a for loop.

In [252]:
def trapz(x, y):
    return 0.5 * np.sum((x[1:] - x[:-1]) * (y[:-1] + y[1:]))

#### Part 4

Verify that your function is correct by using the arrays created in #1 as input to ``trapz``. Your answer should be a close approximation of $\int_0^3 x^2$ which is $9$.

In [253]:
trapz(x, y)

9.055555555555555

#### Part 5 (extension)

``numpy`` and ``scipy.integrate`` provide many common integration schemes.  Find the documentation for NumPy's own version of the trapezoidal integration scheme and check its result with your own:

In [254]:
print np.trapz(y, x)

9.055555555555555


#### Part 6 (extension)

Write a function  `trapzf(f, a, b, npts=100)` that accepts a function `f`, the endpoints `a` and `b` and the number of samples to take `npts`.  Sample the function uniformly at these
points and return the value of the integral.

Use the trapzf function to identify the minimum number of sampling points needed to approximate the integral $\int_0^3 x^2$ with an absolute error of $<=0.0001$. (A loop is necessary here.)

In [255]:
def trapzf(f, a, b, npts=100):
    x = np.linspace(a, b, npts)
    y = f(x)
    return trapz(x, y)

def x_squared(x):
    return x ** 2

abs_err = 1.0
n_samples = 0
expected = 9
while abs_err > 0.0001:
    n_samples += 1
    integral = trapzf(x_squared, 0, 3, npts=n_samples)
    abs_err = np.abs(integral - 9)

print 'Minimum samples for absolute error less than or equal to 0.0001:', n_samples
 

Minimum samples for absolute error less than or equal to 0.0001: 214


## Further Reading <a class="anchor" id="further_reading"></a>

Here are a selection of topics we chose not to include in this workshop, or only touched upon briefly.  You may come across some of them or find these links and terms useful in the future.

### Concepts:

  * [masked arrays](https://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html) and missing data:
  * [NaN](https://docs.scipy.org/doc/numpy/user/misc.html)s and NaN functions
  * boolean arrays and [boolean array indexing](https://docs.scipy.org/doc/numpy/user/basics.indexing.html#boolean-or-mask-index-arrays)
  * matrix multiplication (for example using [dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html))
  * C and Fortran storage order -- see "C order" and "Fortran order" in [the glossary](https://docs.scipy.org/doc/numpy/glossary.html)
  * [file I/O](https://docs.scipy.org/doc/numpy/reference/routines.io.html)
  * [Universal Functions (ufunc)](https://docs.scipy.org/doc/numpy/reference/ufuncs.html)
  * [indexing with arrays of indices](https://docs.scipy.org/doc/numpy/user/basics.indexing.html#index-arrays)

### Functions:

  * [empty](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html)
  * [meshgrid](https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html)
  * [stack](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html), [concatenate](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html#numpy.concatenate) and [split](https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html#numpy.split)
  * [transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html) ([`array.T`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html#numpy.ndarray.T))
  * [roll](https://docs.scipy.org/doc/numpy/reference/generated/numpy.roll.html) and [rollaxis](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html#numpy.rollaxis)